
# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Iterpolation_ALG
                                 A QGIS plugin
 This tool builds DEM from vector isolines.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-08-29
        copyright            : (C) 2020 by Timofey Samsonov
        email                : tsamsonov@geogr.msu.ru
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Timofey Samsonov'
__date__ = '2020-08-29'
__copyright__ = '(C) 2020 by Timofey Samsonov'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Iterpolation_ALG class from file Iterpolation_ALG.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .raster_space import RasterSpacePlugin
    return RasterSpacePlugin()
